const imageURI = {
    ex: require ('../../assets/ex.jpg').default,
    logo: require ('../../assets/logo.png').default,
    banner1: require ('../../assets/banner1.jpg').default,
    banner2: require ('../../assets/banner2.jpg').default,
    banner3: require ('../../assets/banner3.jpg').default,
    banner4: require ('../../assets/banner4.jpg').default,
    banner5: require ('../../assets/banner5.jpg').default,
    banner6: require ('../../assets/banner6.jpg').default,
    recommend1: require ('../../assets/recommend1.jpg').default,
    recommend2: require ('../../assets/recommend2.jpg').default,
    dingo: require ('../../assets/dingo.jpg').default,
    magazin1: require ('../../assets/magazin1.jpg').default,
    magazin2: require ('../../assets/magazin2.jpg').default,
    sns1: require ('../../assets/sns1.jpg').default,
    sns2: require ('../../assets/sns2.jpg').default,
    sns3: require ('../../assets/sns3.jpg').default,
    sns4: require ('../../assets/sns4.jpg').default,
    sns5: require ('../../assets/sns5.jpg').default,
    sns6: require ('../../assets/sns6.jpg').default,
    snsIcon: require ('../../assets/ico_sns.png').default,
    footer1: require ('../../assets/footer1.png').default,
    footer2: require ('../../assets/footer2.png').default,
    footer3: require ('../../assets/footer3.png').default,
    footer4: require ('../../assets/footer4.png').default,
    cart: require ('../../assets/header_icon.png').default,
    glass: require ('../../assets/headicon1.png').default,
    cart1: require ('../../assets/headicon2.png').default,
    arr: require ('../../assets/arrow.png').default,
    arr1: require ('../../assets/arrow1.png').default,
    arr2: require ('../../assets/arrow2.png').default,
    topBtn: require ('../../assets/topbtn.png').default,
    about: require ('../../assets/aboutpage.jpg').default,
    event1: require ('../../assets/event1.jpg').default,
    event2: require ('../../assets/event2.jpg').default,
};

export default imageURI;